# Generated by Django 3.1 on 2020-08-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='viewss',
        ),
    ]
